[[tutorial-comparing-models]]
Comparaison des modèles de données
==================================

Une base de données Graph stocke les données structurées dans les Noeuds et Relatins d'un graphe.
Comment cela est-il comparé à d'autres modèles de persistance?
Du fait qu'un graphe est une structure générique, comparons ce à quoi d'autres modèles auraient l'air dans un graphe.

== Une base de données graphe transforme un SGBDR ==

Renversez la pile d'enregistrements d'une base de données relationnelle et vous verrez un graphe.
Là où un SGBDR est optimisé pour les données aggrégées, Neo4j est optimisé pour les données fortement connectées.

.SGBDR
["dot", "graphdb-compare-rdbms.svg", "meta", scaledwidth="40%"]
----
edge [arrowhead="none" arrowtail="none"]
rankdir="LR"
subgraph cluster_0 {
  color="invis";
  A [shape="record" label="<1>A1|<2>A2|<3>A3"
   fillcolor="NODEHIGHLIGHT"]
}

subgraph cluster_1 {
  color="invis";
  B [shape="record" label="<1>B1|<2>B2|<3>B3|<4>B4|<5>B5|<6>B6|<7>B7"]
}

subgraph cluster_2 {
  color="invis";
  label=""
  C [shape="record" label="<1>C1|<2>C2|<3>C3"
   fillcolor="NODE2HIGHLIGHT"]
}

A:1 -> B:1
A:1 -> B:2
A:2 -> B:4
A:2 -> B:6
A:3 -> B:3
A:3 -> B:5
A:3 -> B:7
C:1 -> B:1
C:1 -> B:4
C:1 -> B:5
C:2 -> B:3
C:2 -> B:7
C:3 -> B:2
C:3 -> B:6
----

.Base de données Graphe comme SGBDR
["dot", "graphdb-compare-rdbms-g.svg", "meta", scaledwidth="100%"]
----
edge [arrowhead="none" arrowtail="none"]

A1 [fillcolor="NODEHIGHLIGHT"]
A2 [fillcolor="NODEHIGHLIGHT"]
A3 [fillcolor="NODEHIGHLIGHT"]

C1 [fillcolor="NODE2HIGHLIGHT"]
C2 [fillcolor="NODE2HIGHLIGHT"]
C3 [fillcolor="NODE2HIGHLIGHT"]

A1 -> B1
A1 -> B2
A2 -> B4
A2 -> B6
A3 -> B3
A3 -> B5
A3 -> B7
C1 -> B1
C1 -> B4
C1 -> B5
C2 -> B3
C2 -> B7
C3 -> B2
C3 -> B6
----


== Une Base de données Graphe conçoit les Stockages Clé-Valeur ==

Un modèle Clé-Valeur est très bien pour la recherche de simples valeurs ou de listes.
Quand ces valeurs sont elle-mêmes interconnectées, vous obtenez un graphe.
Neo4j vous laisse concevoir une simple structure de données en structure données interconnectées et plus complexes.

["dot", "graphdb-compare-kvstore.svg", "meta"]
----
rankdir="LR"

K [shape="record" label="<1>K1|<2>K2|<3>K3" fillcolor="NODEHIGHLIGHT"]
V1 [shape="record" label="<v>V1|K2"]
V2 [shape="record" label="<v>V2|K1|K3"]
V3 [shape="record" label="<v>V3|K1"]

K:1 -> V1:v
K:2 -> V2:v
K:3 -> V3:v
----

+K*+ représente une clé, +V*+ une valeur.
Notez que certaines clés pointent vers d'autres clés comme vers des valeurs.

.Graph Database as Key-Value Store
["dot", "graphdb-compare-kvstore-g.svg", "meta"]
----
rankdir="LR"

gV1 [label="V1"]
gV2 [label="V2"]
gV3 [label="V3"]

subgraph cluster_0 {
  color="invis"
  rank="same"
  K1 [fillcolor="NODEHIGHLIGHT"]
  K2 [fillcolor="NODEHIGHLIGHT"]
  K3 [fillcolor="NODEHIGHLIGHT"]
}

K1 -> gV1
gV1 -> gV2
gV2 -> gV1
gV2 -> gV3
gV3 -> gV1
K2 -> gV2
K3 -> gV3
----

== Une Base de données Graphe conçoit les stockages Orientés Colonnes ==

La famille des stockages Orientés Colonnes (style BigTable) sont une évolution du modèle Clé-Valeur, utilisant des "familles" afin de grouper certaines lignes.
Enregistrées dans un graphe, ces familles peuvent devenir hiérarchiques et les relations entre les données deviennent explicites.


== Une Base de données Graphe navigue à travers un stockage orienté Documents ==

L'hiérarchie en conteneur d'une base de données orientée document conçoit facilement les données non schématisées qui peuvent être représentées en Arbre, qui est évidemment un graphe.
Référez-vous à d'autres documents (ou éléments de documents) au sein de ce même arbre et vous obtenez une représentation plus expressive de ces mêmes données.
Dans Neo4j, ces relations sont facilement naviguables.

.Document Store
["dot", "graphdb-compare-docdb.svg", "meta", scaledwidth="75%"]
----
subgraph cluster_0 {
  color="BOXCOLOR"
  label="D1"
  style="filled"
  fillcolor="NODEHIGHLIGHT"
  subgraph cluster_1 {
    label="S1"
    fillcolor="NODE2HIGHLIGHT"
    V1
    "D2/S2"
  }
}
subgraph cluster_2 {
  color="BOXCOLOR"
  label="D2"
  style="filled"
  fillcolor="NODEHIGHLIGHT"
  subgraph cluster_3 {
    label="S2"
    fillcolor="NODE2HIGHLIGHT"
    V2
    V3
  }
  subgraph cluster_4 {
    label="S3"
    fillcolor="NODE2HIGHLIGHT"
    V4
    "D1/S1"
  }
}
----

+D+=Document, +S+=Sousdocument, +V+=Valeur, +D2/S2+ = Référence à un Sousdocument dans un (autre) Document.

.Graph Database as Document Store
["dot", "graphdb-compare-docdb-g.svg", "meta", scaledwidth="75%"]
----
rankdir="LR"

subgraph cluster_0 {
  color="invis"
  D1 [fillcolor="NODEHIGHLIGHT"]
  D2 [fillcolor="NODEHIGHLIGHT"]
}

subgraph cluster_1 {
  color="invis"
  rank="TB"
  S1 [fillcolor="NODE2HIGHLIGHT"]
  S2 [fillcolor="NODE2HIGHLIGHT"]
  S3 [fillcolor="NODE2HIGHLIGHT"]
}

D1 -> S1 -> V1
D2 -> S2 -> V2
D2 -> S3 -> V4
S1 -> S2
S2 -> V3
S3 -> S1
----


